<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="TestBuildersHowItWorks" tests="1" skipped="0" failures="1" errors="0" timestamp="2023-03-30T04:07:51" hostname="MZS01-ALLENDEVui-MacBookPro.local" time="0.007">
  <properties/>
  <testcase name="testBuildersQuiz" classname="TestBuildersHowItWorks" time="0.007">
    <failure message="java.lang.AssertionError: Your answers for questions [3, 4] are incorrect" type="java.lang.AssertionError">java.lang.AssertionError: Your answers for questions [3, 4] are incorrect
	at org.junit.Assert.fail(Assert.java:88)
	at TestBuildersHowItWorks.testBuildersQuiz(tests.kt:18)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
</failure>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
